apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "backend.fullname" . }}-prestart
  labels:
    {{- include "backend.labels" . | nindent 4 }}
    app.kubernetes.io/component: prestart
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "backend.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: prestart
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Never
      containers:
        - name: prestart
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - bash
            - scripts/prestart.sh
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
