{{- if .Values.cnpg.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "helm-chart.fullname" . }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  instances: {{ .Values.cnpg.instances | default 1 }}
  postgresql:
    parameters:
      timezone: {{ .Values.config.TZ | quote }}
  storage:
    size: {{ .Values.cnpg.storageSize | default "10Gi" }}
  bootstrap:
    initdb:
      database: {{ .Values.config.database }}
      owner: {{ .Values.config.owner }}
      secret:
        name: {{ include "helm-chart.fullname" . }}
  backup:
    barmanObjectStore:
      destinationPath: {{ .Values.cnpg.backup.destinationPath | default "s3://postgres-backup/" }}
      endpointURL: {{ .Values.cnpg.backup.endpointURL | default "http://seaweedfs-stag:9000" }}
      s3Credentials:
        accessKeyId:
          name: {{ .Values.cnpg.backup.secretName | default "seaweedfs-secret" }}
          key: {{ .Values.cnpg.backup.accessKeyIdKey | default "S3_USER" }}
        secretAccessKey:
          name: {{ .Values.cnpg.backup.secretName | default "seaweedfs-secret" }}
          key: {{ .Values.cnpg.backup.secretAccessKeyKey | default "S3_PASSWORD" }}
      wal:
        compression: gzip

{{- end }}
