{{- if .Values.cnpg.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "helm-chart.fullname" . }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  instances: {{ .Values.cnpg.instances | default 1 }}
  imageName: {{ .Values.cnpg.imageName | default "ghcr.io/cloudnative-pg/postgresql:16" }}
  {{- with .Values.cnpg.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  postgresql:
    parameters:
      timezone: {{ .Values.config.TZ | quote }}
      {{- if .Values.cnpg.pgvector.enabled }}
      shared_preload_libraries: "vectors.so"
      {{- end }}
  storage:
    size: {{ .Values.cnpg.storageSize | default "10Gi" }}
  bootstrap:
    initdb:
      database: {{ .Values.config.database }}
      owner: {{ .Values.config.owner }}
      secret:
        name: {{ include "helm-chart.fullname" . }}
      {{- if .Values.cnpg.pgvector.enabled }}
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS vector
        - CREATE EXTENSION IF NOT EXISTS vectors
      {{- end }}
  backup:
    barmanObjectStore:
      destinationPath: {{ dig "backup" "destinationPath" "s3://postgres-backup/" .Values.cnpg }}
      endpointURL: {{ dig "backup" "endpointURL" "http://seaweedfs-stag:9000" .Values.cnpg }}
      s3Credentials:
        accessKeyId:
          name: {{ dig "backup" "secretName" "seaweedfs-secret" .Values.cnpg }}
          key: {{ dig "backup" "accessKeyIdKey" "S3_USER" .Values.cnpg }}
        secretAccessKey:
          name: {{ dig "backup" "secretName" "seaweedfs-secret" .Values.cnpg }}
          key: {{ dig "backup" "secretAccessKeyKey" "S3_PASSWORD" .Values.cnpg }}
      wal:
        compression: gzip

{{- end }}
