{{- if .Values.cnpg.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "helm-chart.fullname" . }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  instances: {{ .Values.cnpg.instances | default 1 }}
  {{- with .Values.cnpg.imageName }}
  imageName: {{ . }}
  {{- end }}
  {{- with .Values.imagePullSecrets }}
  imagePullSecrets:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.cnpg.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  postgresql:
    parameters:
      timezone: {{ .Values.config.TZ | quote }}
      {{- if .Values.cnpg.sharedBuffers }}
      shared_buffers: {{ .Values.cnpg.sharedBuffers | quote }}
      {{- end }}
  affinity:
    enablePodAntiAffinity: {{ .Values.cnpg.enablePodAntiAffinity | default false }}
    topologyKey: {{ .Values.cnpg.topologyKey | default "kubernetes.io/hostname" | quote }}
  storage:
    size: {{ .Values.cnpg.storageSize | default "10Gi" }}
    {{- with .Values.cnpg.storageClass }}
    storageClass: {{ . }}
    {{- end }}
  bootstrap:
    initdb:
      database: {{ .Values.config.database }}
      owner: {{ .Values.config.owner }}
      secret:
        name: {{ include "helm-chart.fullname" . }}
      postInitApplicationSQL:
        - "CREATE EXTENSION IF NOT EXISTS vector;"
        - "CREATE DATABASE {{ .Values.config.applicationDatabase }} OWNER {{ .Values.config.owner }};"
  backup:
    retentionPolicy: {{ dig "backup" "retentionPolicy" "30d" .Values.cnpg | quote }}
    barmanObjectStore:
      destinationPath: {{ dig "backup" "destinationPath" "s3://postgres-backup/" .Values.cnpg }}
      endpointURL: {{ dig "backup" "endpointURL" "http://seaweedfs-stag:9000" .Values.cnpg }}
      s3Credentials:
        accessKeyId:
          name: {{ dig "backup" "secretName" "seaweedfs-secret" .Values.cnpg }}
          key: {{ dig "backup" "accessKeyIdKey" "S3_USER" .Values.cnpg }}
        secretAccessKey:
          name: {{ dig "backup" "secretName" "seaweedfs-secret" .Values.cnpg }}
          key: {{ dig "backup" "secretAccessKeyKey" "S3_PASSWORD" .Values.cnpg }}
      wal:
        compression: gzip

{{- end }}
