apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "helm-chart.fullname" . }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  encryptedData:
    username: {{ .Values.secret.DB_USER | quote }}
    password: {{ .Values.secret.DB_PASS | quote }}
  template:
    metadata:
      name: {{ include "helm-chart.fullname" . }}
      labels:
        {{- include "helm-chart.labels" . | nindent 8 }}
    type: kubernetes.io/basic-auth
