apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "helm-chart.fullname" . }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  encryptedData:
    {{- range $key, $value := .Values.secret }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  template:
    metadata:
      name: {{ include "helm-chart.fullname" . }}
      labels:
        {{- include "helm-chart.labels" . | nindent 8 }}
    type: kubernetes.io/basic-auth
