apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-chart.fullname" . }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.config.DB_USER | quote }}
  password: {{ .Values.secret.DB_PASS | quote }}
