services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - gitea
    networks:
      - platform_net
  gitea:
    image: ghcr.io/nguyentukien/platform-service:latest
    container_name: gitea
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__APP_NAME=Git Platform
      - GITEA__server__DOMAIN
      - GITEA__server__ROOT_URL
      - GITEA__server__SSH_DOMAIN
      - GITEA__server__SSH_PORT=2222
      - GITEA__server__DISABLE_SSH=false
      - GITEA__server__LFS_START_SERVER=true
      - GITEA__service__DISABLE_REGISTRATION=false
      - GITEA__service__ALLOW_ONLY_EXTERNAL_REGISTRATION=true
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=postgres:5432
      - GITEA__database__NAME
      - GITEA__database__USER
      - GITEA__database__PASSWD
      - GITEA__server__LANDING_PAGE=explore
      - GITEA__actions__ENABLED=true
      - GITEA__oauth2_client__ACCOUNT_LINKING=auto
      - GITEA__oauth2_client__UPDATE_AVATAR=true
      - GITEA__oauth2_client__ENABLE_AUTO_REGISTRATION=true
      - GITEA__oauth2_client__USERNAME=preferred_username
      - GITEA__service__VALID_USERNAME_CHARS=a-zA-Z0-9_-.
    volumes:
      - gitea_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2222:22"
    networks:
      - platform_net

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - platform_net

  minio:
    image: minio/minio:RELEASE.2024-06-22T05-26-45Z
    container_name: minio
    command: server /data --console-address ":9001"
    restart: unless-stopped
    environment:
      - MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - platform_net

volumes:
  gitea_data:
  postgres_data:
  minio_data:

networks:
  platform_net:
    driver: bridge
