apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-chart.fullname" . }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "helm-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "helm-chart.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "helm-chart.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: init-s3-config
          image: busybox
          command:
            - sh
            - -c
            - |
              cat <<EOF > /etc/seaweedfs/s3.json
              {
                "identities": [
                  {
                    "name": "admin",
                    "credentials": [
                      {
                        "accessKey": "$S3_USER",
                        "secretKey": "$S3_PASSWORD"
                      }
                    ],
                    "actions": ["Admin", "Read", "Write"]
                  }
                ]
              }
              EOF
          envFrom:
            - secretRef:
                name: seaweedfs-secret
          volumeMounts:
            - name: config
              mountPath: /etc/seaweedfs
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["weed", "server", "-dir=/data", "-s3", "-s3.port=9000", "-s3.config=/etc/seaweedfs/s3.json"]
          envFrom:
            - secretRef:
                name: seaweedfs-secret
          {{- if .Values.config }}
          env:
            {{- $keys := keys .Values.config | sortAlpha }}
            {{- range $keys }}
            - name: {{ . }}
              value: {{ index $.Values.config . | quote }}
            {{- end }}
          {{- end }}
          ports:
            - name: api
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: master
              containerPort: {{ .Values.service.masterPort }}
              protocol: TCP
            - name: filer
              containerPort: {{ .Values.service.filerPort }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
            - name: config
              mountPath: /etc/seaweedfs
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "helm-chart.fullname" . }}
        - name: config
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
