---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: seaweedfs-secret
  namespace: default
spec:
  encryptedData:
    WEED_S3_USER: {{ .Values.secret.S3_USER | quote }}
    WEED_S3_PASSWORD: {{ .Values.secret.S3_PASSWORD | quote }}
  template:
    metadata:
      creationTimestamp: null
      name: seaweedfs-secret
      namespace: default
