---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: seaweedfs-secret
  namespace: default
spec:
  encryptedData:
    {{- range $key, $value := .Values.secret }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  template:
    metadata:
      creationTimestamp: null
      name: seaweedfs-secret
      namespace: default
