replicaCount: 1

strategy:
  type: Recreate

image:
  repository: chrislusf/seaweedfs
  pullPolicy: IfNotPresent
  tag: "3.75"

persistence:
  enabled: true
  size: 20Gi
  storageClass: local-path

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

mcImage:
  repository: minio/mc
  pullPolicy: IfNotPresent
  tag: "latest"

buckets:
  - gitea-backup
  - postgres-backup

imagePullSecrets: []

secret:
  S3_USER: "<ENCRYPTED_S3_USER>"
  S3_PASSWORD: "<ENCRYPTED_S3_PASSWORD>"

config:
  TZ: "Asia/Ho_Chi_Minh"

nameOverride: "seaweedfs"
fullnameOverride: "seaweedfs"

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 9000
  masterPort: 9333
  filerPort: 8888

resources: {}

livenessProbe:
  tcpSocket:
    port: 9000
  initialDelaySeconds: 15
  periodSeconds: 20
readinessProbe:
  tcpSocket:
    port: 9000
  initialDelaySeconds: 15
  periodSeconds: 20

autoscaling:
  enabled: false

volumeMounts:
  - name: data
    mountPath: /data

nodeSelector: {}
tolerations: []
affinity: {}
