replicaCount: 1

cnpg:
  enabled: true
  instances: 1
  storageSize: 10Gi

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "postgres"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}

config:
  owner: "gitea"
  database: "gitea"
  TZ: "Asia/Ho_Chi_Minh"

secret:
  username: "<ENCRYPTED_DB_USER>"
  password: "<ENCRYPTED_DB_PASSWORD>"