# Default values for helm-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

strategy:
  type: Recreate

extraPorts:
  - name: ssh
    containerPort: 22
    protocol: TCP

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi



# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: ghcr.io/nguyentukien/platform-service
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "535f6f3e5d6c682cee37f02dd1ca585267a4c90c"

# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: "gitea"

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 3000

# This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# -- Expose the service via gateway-api HTTPRoute
# Requires Gateway API resources and suitable controller installed within the cluster
# (see: https://gateway-api.sigs.k8s.io/guides/)
httpRoute:
  # HTTPRoute enabled.
  enabled: false
  # HTTPRoute annotations.
  annotations: {}
  # Which Gateways this Route is attached to.
  parentRefs:
  - name: gateway
    sectionName: http
    # namespace: default
  # Hostnames matching HTTP header.
  hostnames:
  - chart-example.local
  # List of rules and filters applied.
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /headers
  #   filters:
  #   - type: RequestHeaderModifier
  #     requestHeaderModifier:
  #       set:
  #       - name: My-Overwrite-Header
  #         value: this-is-the-only-value
  #       remove:
  #       - User-Agent
  # - matches:
  #   - path:
  #       type: PathPrefix
  #       value: /echo
  #     headers:
  #     - name: version
  #       value: v2

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 5
readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

# This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes:
  - name: timezone
    hostPath:
      path: /etc/timezone
  - name: localtime
    hostPath:
      path: /etc/localtime
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts:
  - name: timezone
    mountPath: /etc/timezone
    readOnly: true
  - name: localtime
    mountPath: /etc/localtime
    readOnly: true
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}

config:
  GITEA__APP_NAME: "Git Platform"
  GITEA__server__LFS_START_SERVER: "true"
  GITEA__database__DB_TYPE: "postgres"
  GITEA__database__HOST: "postgres-rw:5432"
  GITEA__database__NAME: "gitea"
  USER_UID: "1000"
  USER_GID: "1000"
  GITEA__server__DOMAIN: "git.ngtukien.id.vn"
  GITEA__server__ROOT_URL: "https://git.ngtukien.id.vn/"
  GITEA__server__SSH_DOMAIN: "git.ngtukien.id.vn"
  GITEA__server__SSH_PORT: "2222"
  GITEA__server__DISABLE_SSH: "false"
  GITEA__service__DISABLE_REGISTRATION: "false"
  GITEA__service__ALLOW_ONLY_EXTERNAL_REGISTRATION: "true"
  GITEA__server__LANDING_PAGE: "explore"
  GITEA__actions__ENABLED: "true"
  GITEA__oauth2_client__ACCOUNT_LINKING: "auto"
  GITEA__oauth2_client__UPDATE_AVATAR: "true"
  GITEA__oauth2_client__ENABLE_AUTO_REGISTRATION: "true"
  GITEA__oauth2_client__USERNAME: "preferred_username"
  GITEA__service__VALID_USERNAME_CHARS: 'a-zA-Z0-9_-.'

secret:
  GITEA__database__USER: "AgAL0iMxXnWMwSKEuFMXWaqoMJU5E50n69a26yBLpiwgX7aBNuyoRnzK5i142/pmP4TAijpA27uVpAKgt8kCZWOz/gAFdQc0blWFaE9YIif3iweS8OeabscTcM/hLqJzKKupVJfhn/hk7QShLYJnIm/+ltX0D6Bc09OjA1UzBzQCfAvH/uMUbIVDz5t4rnJVTLwv6FVDxrLd3W5SaKO2TDBmSK13jwpjHz2hg1Fitz/kFcYYyHxFDkR4aNUw96sD+C1HPQO30Kd0cdDKZQg9QzkGrxUqhnqHxz/h35zVexUx7dTf+ricdGJ1EtumJExLjHDzpW8cOIiQoNDThzY0JkEdmVOZ9ruXsEgXb04m0xSu2ver23HJEbpOK3xgnEcqkGNuagv/81avFs5Ztx5JvbY3ZhjAfHaFPKmL6B1v7lzv3BmonQ0unlL8FZHeTdKnAhAyYxbjrRqN5i3i+WeiXZmmkg6N5lIRU/TASwBzbcb8w/YCEqn1JZoFwlmRwoXBnJV5waP123VbJ+0paA3N5JjTpjQHqY62LSVoCytLvKeFKeG9qHJRdmwBS/jG71/qON1sotgT6Xytlcs32npAMdjrp9Ga9apQNGQZJQh46Ejrq7gH+f52V85X2zn+tOtfPNzcxs//71F1JsbV/F1YkDYcr4tR7Ke4n/z3RhlaX3cxluv3FcJMfH9L2HqGbjBth31R+iNaDw=="
  GITEA__database__PASSWD: "AgARbspAyAfqHUVyMWdhp4jyoPJ82f8kHljYHJte8CNDMnJbnSdn7K9C2fLiv2qNlgcrzoMiL61jQhMX9Qt2pmAYC5YnEzn3KG6Sz2Y2O7ObcwjUi8dVV/cwri6E8qR4EP7J6kepP5uElfmWSmyrGQuGsVkOuBVJgJRJws+oOetRNn1X9clZdUODsSRy0mx8UCeazOYd48F6Dmg2UuSnhsVpndClC1NDppueyZc0MqL432LTAH42BXfDGrSA9Zz5CYHSnpe+dVHqeIFl5q+6Z7FkHDFh61d9oAMwwYOZDtgjBxleE/GIenRpnHtFsm7bz1sDOQ2IXaZC0511zSWPmMbcSxPIIEhAww3PIQ4Z4SEDq6LVprI4rqAdHx87nmBpilG/dKRBZ0ehCNNDJs52fQASbbQN1NBjvVh3BSw7A4KQwZCXkb4huIKT28kjLw4ZuHRB2TnFeqsJ5c7xWkLXvgtYA965in5gLOapfuvnye0kHG0qqgVndgGUqem7OW+fO++vvWqcq5sSGWTZ9m+PwiO61RgBAmwU1iiauAHivdwH5VD+89BG/yqWWRqbbE358H50LeZ6lpiIap/zipY+V9ekkXrUtJ82wZWFQDcVX7OrAEzBIY81JoJXTiMEaaln+gxD1dPloH4tIvTXy7TS8SXVXjU12XG4pBzHnMkXTP7MK+kYQ0vKJg5Y33KsqQAF9Kz3IGbaz23ly/1A5zdZdVnVnCMzO1IqNPd0"