replicaCount: 1

strategy:
  type: Recreate

extraPorts:
  - name: ssh
    containerPort: 22
    protocol: TCP

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 5Gi

image:
  repository: ghcr.io/nguyentukien/nits-platform
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "gitea"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

initContainers: []

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 3000

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 512Mi

livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 30
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 5

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}

config:
  TZ: "Asia/Ho_Chi_Minh"
  GITEA__APP_NAME: "Git Platform"
  GITEA__server__LFS_START_SERVER: "true"
  GITEA__database__DB_TYPE: "postgres"
  GITEA__database__HOST: "postgres-rw:5432"
  GITEA__database__NAME: "gitptit"
  USER_UID: "1000"
  USER_GID: "1000"
  GITEA__server__DOMAIN: "git.example.com"
  GITEA__server__ROOT_URL: "https://git.example.com/"
  GITEA__server__SSH_DOMAIN: "git.example.com"
  GITEA__server__SSH_PORT: "2222"
  GITEA__server__DISABLE_SSH: "false"
  GITEA__service__DISABLE_REGISTRATION: "false"
  GITEA__service__ALLOW_ONLY_EXTERNAL_REGISTRATION: "true"
  GITEA__server__LANDING_PAGE: "explore"
  GITEA__actions__ENABLED: "true"
  GITEA__oauth2_client__ACCOUNT_LINKING: "auto"
  GITEA__oauth2_client__UPDATE_AVATAR: "true"
  GITEA__oauth2_client__ENABLE_AUTO_REGISTRATION: "true"
  GITEA__oauth2_client__USERNAME: "preferred_username"
  GITEA__service__VALID_USERNAME_CHARS: 'a-zA-Z0-9_-.'
