apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-chart.fullname" . }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
data:
  LDAP_ORGANISATION: {{ .Values.config.LDAP_ORGANISATION | quote }}
  LDAP_DOMAIN: {{ .Values.config.LDAP_DOMAIN | quote }}
  LDAP_BASE_DN: {{ .Values.config.LDAP_BASE_DN | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-chart.fullname" . }}-ldif
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
data:
  01-seed-users.ldif: |
    # Organizational Units
    dn: ou=users,{{ .Values.config.LDAP_BASE_DN }}
    objectClass: organizationalUnit
    ou: users

    {{- range .Values.seedUsers }}
    # User: {{ .uid }}
    dn: uid={{ .uid }},ou=users,{{ $.Values.config.LDAP_BASE_DN }}
    objectClass: inetOrgPerson
    objectClass: posixAccount
    objectClass: shadowAccount
    uid: {{ .uid }}
    cn: {{ .cn }}
    sn: {{ .sn }}
    mail: {{ .mail }}
    uidNumber: 10001
    gidNumber: 10001
    homeDirectory: /home/{{ .uid }}
    userPassword: {{ .password }}

    {{- end }}
