apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-chart.fullname" . }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  LDAP_ADMIN_PASSWORD: {{ .Values.secret.LDAP_ADMIN_PASSWORD | quote }}
