---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-secret
  namespace: default
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgBGoMzgQ5eETkJbrzf5OOSzJ3jhE59sSjeVozlOG/8H9uQL776kiTq9R/Wi35YRMKOpEmM4aO2Xuv5v5Hglp/psUR2mp/3QdnG01GSG7ALgLeiPuFBz2xfzQyKCsGrOSxXQOUUJQWbm62RYSax9mkwjPCzl9SLLO796slgKQzF5wjf2tm4aJ8hZ7NqtbVPsznqbHAITYCC6F/q0ZvJc7SCRduHmcadC5FelRG1mkmAMM9wJR/ifgaaTVDc6KyHpPstBorgYWo59tedsBwYPL+BN9JPfhnU1BK1ugbpsc0G1mDfWq6IIsf87sxyqxmc+IrrDtOTg0p6MX8a0bzJNUsuZYOnabnsNL2aatzGVfcSCscNU4AI8T1nymbN16dTxUhXZGxmkSHMn2flu4KHecA1JqeYafwjcAPjb43v3WhYgJXQ0JfTjRhsqWH8kk5tMqsbTKI7u1E0Fz8rAR5nt0WqD7DGWp+NusHlMjRM50DqlLd9Z3DYUY2KgKR3mi2psdFp1xtU491ABIPUGqkTlBKhe9TMAFhDpenptLR6UyGighaP+Y/w/kG4z+LBq+bZ0u5Q0i0pKuPxeeS7h0+6n84Ty1unHJRY5YQnnVa50rf37DQgkZERDd6iNRn6FP9/yJqaOVU2nDMhFy/T/FXeldT/NI6m3VaQPkrXQtMHuLlgtZLgAGfrS+nxLkLSssadI0YxRsf7i13XH8WnPN1dkADM=
    MINIO_ROOT_USER: AgCFOh179taNSBa1+UUIIlOPw2tOGeuP1l4m2L9JEsdh4ld8ExLFaFnw9++jp2qc3XhTwKg5N9cmPGTMup6p4UN7YTi+yUBE1r/bXFxqXYlHg+FyX11eDn3pfINIZlxk+xgx5I/p98lmG/JOwQq6tn5lBG31QqV9MLmeOhe/IO3EcKc2UXEznYLnYQqItUS+2g1Z1J/aHSjplUgofFrmmGbibqmXBwDUSufIJtLesskhH+tC0I7s22a8iVzLGzP9MzxNz17g9S+NLniOpdjR/HDXh8IQZdpiZwZZhtlyxcuadqjmZSmtxs09bLze/1wd0iYz/UidrbQWzSgaPTjUG165RejaPw9QeIJozjxSy3kTmbJ4fMvktfC367o7j8j94ryaYhGrDWLTstRF8GTNboDjdVZWF2ArpMYsQJ7gUo4dxJcNziqoLUIX6vIKTm2pNGQIXnFst1l3Obe3G/DUl8CZV/8hiJU+PjpEkfNGggR/38w+nSVBHCVsc68Cs7Ry7EP4hVYSUXToi6Wkxmb8qqbDU4Dj9Nia4DpGnyq45nYeBulvptPdWOot57ANijg+EKC4vzY1LJS7mSy7aEq6nleXXOWR+pnQCX30mp5hLNKQHZmqEyNtH4rKNLo7JUO1g7OjGLWu4ne7sPKuVLdG7UAJa7wynXYam3BMeFAwrqhkfPw2LfMCsHd9OvLp/U3wMtm5NuFHag==
  template:
    metadata:
      creationTimestamp: null
      name: minio-secret
      namespace: default
