---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-secret
spec:
  encryptedData:
    {{- $keys := keys .Values.secret | sortAlpha }}
    {{- range $keys }}
    {{ . }}: {{ index $.Values.secret . | quote }}
    {{- end }}
  template:
    metadata:
      name: minio-secret
