---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-secret
  namespace: default
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: {{ .Values.secret.MINIO_ROOT_PASSWORD | quote }}
    MINIO_ROOT_USER: {{ .Values.secret.MINIO_ROOT_USER | quote }}
  template:
    metadata:
      creationTimestamp: null
      name: minio-secret
      namespace: default
