apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: git-platform-set
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/AI-Teaching-Assistant-PTIT/git-platform.git
              revision: HEAD
              directories:
                - path: '*/helm-chart'
          - list:
              elements:
                - env: stag
                # - env: prod
  template:
    metadata:
      name: '{{path[0]}}-{{env}}'
    spec:
      project: default
      sources:
        - repoURL: https://github.com/AI-Teaching-Assistant-PTIT/git-platform.git
          targetRevision: HEAD
          path: '{{path}}'
          helm:
            valueFiles:
              - '$values/{{path[0]}}/{{env}}/values.yaml'
        - repoURL: https://github.com/AI-Teaching-Assistant-PTIT/config-repo.git
          targetRevision: main
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      ignoreDifferences:
        - group: postgresql.cnpg.io
          kind: Cluster
          jsonPointers:
            - /spec/postgresql/parameters
            - /spec/resources
            - /spec/affinity/podAntiAffinityType
            - /spec/backup/target
            - /spec/enablePDB
            - /spec/enableSuperuserAccess
            - /spec/failoverDelay
            - /spec/logLevel
            - /spec/maxSyncReplicas
            - /spec/minSyncReplicas
            - /spec/primaryUpdateMethod
            - /spec/primaryUpdateStrategy
            - /spec/replicationSlots
            - /spec/smartShutdownTimeout
            - /spec/startDelay
            - /spec/stopDelay
            - /spec/switchoverDelay
            - /spec/monitoring
            - /spec/postgresql/syncReplicaElectionConstraint
            - /spec/postgresGID
            - /spec/postgresUID
