replicaCount: 1

fullnameOverride: "openldap"

image:
  repository: osixia/openldap
  tag: "1.5.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 389

persistence:
  enabled: true
  size: 1Gi
  accessMode: ReadWriteOnce

config:
  LDAP_ORGANISATION: "PTIT"
  LDAP_DOMAIN: "ptit.edu.vn"
  LDAP_BASE_DN: "dc=ptit,dc=edu,dc=vn"

secret:
  LDAP_ADMIN_PASSWORD: "Admin1234"

# Seed data - users for testing
seedUsers:
  - uid: "sv001"
    cn: "Nguyen Van A"
    sn: "Nguyen"
    mail: "sv001@stu.ptit.edu.vn"
    password: "Ptit1234"
  - uid: "sv002"
    cn: "Tran Thi B"
    sn: "Tran"
    mail: "sv002@stu.ptit.edu.vn"
    password: "Ptit1234"
