replicaCount: 1

strategy:
  type: Recreate

image:
  repository: minio/minio
  pullPolicy: IfNotPresent
  tag: "RELEASE.2025-04-22T22-12-26Z"

persistence:
  enabled: true
  size: 20Gi
  storageClass: local-path

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

mcImage:
  repository: minio/mc
  pullPolicy: IfNotPresent
  tag: "latest"

buckets:
  - gitea-backup
  - postgres-backup

imagePullSecrets: []

secret:
  MINIO_ROOT_USER: "<ENCRYPTED_MINIO_ROOT_USER>"
  MINIO_ROOT_PASSWORD: "<ENCRYPTED_MINIO_ROOT_PASSWORD>"

config:
  TZ: "Asia/Ho_Chi_Minh"
  MINIO_VOLUMES: "/data"

nameOverride: "minio"
fullnameOverride: "minio"

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 9000        # S3 API port
  consolePort: 9001 # Web Console port

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 1Gi

livenessProbe:
  httpGet:
    path: /minio/health/live
    port: 9000
  initialDelaySeconds: 30
  periodSeconds: 20
readinessProbe:
  httpGet:
    path: /minio/health/ready
    port: 9000
  initialDelaySeconds: 30
  periodSeconds: 20

autoscaling:
  enabled: false

volumeMounts:
  - name: data
    mountPath: /data

nodeSelector: {}
tolerations: []
affinity: {}
