replicaCount: 1

config:
  TZ: "Asia/Ho_Chi_Minh"

secret:
  TUNNEL_TOKEN: "<ENCRYPTED_TUNNEL_TOKEN>"

args:
  - tunnel
  - --no-autoupdate
  - run

image:
  repository: cloudflare/cloudflared
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "cloudflare"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 20m
    memory: 64Mi

livenessProbe: {}
readinessProbe: {}

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
