# Default values for helm-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

strategy:
  type: Recreate

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi

config:
  GITEA_INSTANCE_URL: "http://gitea:3000"

secret:
  GITEA_RUNNER_REGISTRATION_TOKEN: "AgAlv87N6evw5rm8kmyybC5v1c9ZBoztIvL5l3mTMNWM0MbrzZqg/L2JslUVoqrtzVVgS8bKsAWYk0BGTI2uC/qq5LbnOlXiwrQPaecNzYBLydzQ8l3+PCa4bWM6QJ/GEKbEgy8Upgq901WJexlef4QEKAp/H7hxUDQNs6zCOIe7GS5Z5mLum3euepwhEeUzJxnDIhj4/V4W8WHlW6svpCabUOz8jF11Nv6qXq8eMLphqSdQrMU8/UyWM0AQE2KXk+zgH8uRI0BNxfDhMrizGayDGkr3NwbZIPoCypjN3s3d2AU3qHaa6HQ0rgow5CbydEvbH/vEFr4WiCRVN2uli8U0oDTCMk4g6wOM49jf6+hjabb/t3TuTSWUteLeNXL821L1A3UCj+nC5joq+xLbbKXzZtNZgdPFRBcg6FC21j2L5UBSyuBTkOMaOC43YEK/StrBDKm4Iteycj4Swg0PE+kIp75FWtkyAMVL04kF+fJ/MmdA30EnqfEznj4DB5St2ob/mM2b8SdK3I7WM560BCUgHNLWeERs065MQQAd+P7em9+dgShs3cPOsV4Vexz4EPmLNOk8MKHmHUoJHHbjaYXrHnLyLrp99YrI1mZhpFKKH+Z4IQd+wBmxFgXkXyBDjRFO2YPyg/TzMB64LZuEicsC1slGz8nRsk85AcbQU0bcJtRR35EfLa0xn/vfUqrVfcZw7i3WtT+lMR/zhrpgVYg5mx6TuOaJJZuQvgZBIBdJKGVeAQ0aBU+P"

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: gitea/act_runner
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest-dind"

# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: "runner"

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

securityContext:
  privileged: true

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 80

# This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# -- Expose the service via gateway-api HTTPRoute
# Requires Gateway API resources and suitable controller installed within the cluster
# (see: https://gateway-api.sigs.k8s.io/guides/)
httpRoute:
  # HTTPRoute enabled.
  enabled: false
  # HTTPRoute annotations.
  annotations: {}
  # Which Gateways this Route is attached to.
  parentRefs:
  - name: gateway
    sectionName: http
    # namespace: default
  # Hostnames matching HTTP header.
  hostnames:
  - chart-example.local
  # List of rules and filters applied.
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /headers
  #   filters:
  #   - type: RequestHeaderModifier
  #     requestHeaderModifier:
  #       set:
  #       - name: My-Overwrite-Header
  #         value: this-is-the-only-value
  #       remove:
  #       - User-Agent
  # - matches:
  #   - path:
  #       type: PathPrefix
  #       value: /echo
  #     headers:
  #     - name: version
  #       value: v2

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe: {}
readinessProbe: {}

# This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.

# Additional volumeMounts on the output Deployment definition.

nodeSelector: {}

tolerations: []

affinity: {}
